version: '3.2'

services:
  api:
    build: ./
    container_name: qlub_challenge
    image: qlub_challenge:latest
    env_file:
      - ./.env
    command: python3 main.py
    ports:
      - 5000:5000
    volumes:
      - source: ./
        target: /src
        type: bind
